services:
  db:
    image: mysql
    container_name: exercise_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_DOCKER}
      MYSQL_DATABASE: ${MYSQL_DATABASE_DOCKER}
      # Best practice to create a non-root user for app
      MYSQL_USER: ${MYSQL_USER_DOCKER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_DOCKER}

    ports:
      - "${DB_PORT_DOCKER}:3306"

    volumes:
      - mysql_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin
    container_name: exercise_pma
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_DOCKER}
    ports:
      - "${PMA_PORT_DOCKER}:80"


volumes:
  mysql_data: